services:
  php:
    env_file:
      - .env.local
    environment:
      APP_ENV: prod
      APP_DEBUG: 0

  nginx:
    ports: []

  database:
    ports: []

  phpmyadmin:
    profiles: ['tools']
    ports: []

  caddy:
    image: caddy:2
    depends_on:
      - nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
